version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "execution-engine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x9ffojejk6cw"
s3_prefix = "execution-engine"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
